# Generated by Django 5.1.2 on 2025-08-27 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("cnpj", models.CharField(max_length=18, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("os_number", models.CharField(max_length=50)),
                ("service_name", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("scheduled_date", models.DateField()),
                ("service_provider", models.CharField(max_length=255)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to="regular.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConstitutiveDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doc_name", models.CharField(max_length=255)),
                ("doc_url", models.URLField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="constitutive_documents",
                        to="regular.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Finance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("due_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("invoice", models.CharField(max_length=255)),
                ("contract", models.CharField(max_length=255)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finances",
                        to="regular.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RenewableDoc",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("doc_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("os_number", models.CharField(max_length=50)),
                ("renewed_at", models.DateField()),
                ("expiration_date", models.DateField()),
                ("doc_url", models.URLField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="renewable_docs",
                        to="regular.company",
                    ),
                ),
            ],
        ),
    ]
