# Generated by Django 5.1.2 on 2025-08-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regular", "0002_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="constitutivedocument",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="finance",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
