# Generated by Django 5.1.2 on 2025-08-31 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regular", "0003_alter_budget_id_alter_constitutivedocument_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="doc_url",
            field=models.URLField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="finance",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="finance",
            name="contract",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="finance",
            name="invoice",
            field=models.URLField(),
        ),
    ]
