# Generated by Django 5.1.2 on 2025-09-08 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regular", "0005_userprofile_companies_alter_userprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="renewabledoc",
            name="alert_sent",
            field=models.BooleanField(default=False),
        ),
    ]
