# Generated by Django 5.1.2 on 2025-10-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regular', '0006_renewabledoc_alert_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
